---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
  namespace: openspeedtest
  labels:
    app: openspeedtest
spec:
  type: ClusterIP
  selector:
    app: openspeedtest
  ports:
    - port: 80
      targetPort: 3000
      name: http
