apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DOrTyKiy85DgLIicsIybzoUK6cc5BjmYEg==,iv:WNyfqJjaEmMPwvrchLS0GEX4B3XUnBCY34VQFmyqfz0=,tag:ndO7I6tR4FWGbHOGnfNKMg==,type:str]
    password: ENC[AES256_GCM,data:wk7S9VD66zUhtO7ysOdsdxNu9sZe5eAJT0NmIiNV,iv:pRWhnhnJZVo6hmaxWSDOyN5H9oFypNpr++ZZNRExCYQ=,tag:6dTG75dioIK1BpWr1uIfUw==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQkJxZkFaRHdDQ1YvRVlw
            NFFzeWhuazRXOThaS1MzN1ZnbnRrMjRudm1VClg1SnNWOWdxaGpjM3Zja0RLRDZP
            NGZ4QlVxVStid3B2RlFNVldIZ0x0ZjQKLS0tIHJhZkpCc0UxTzZ1bjlCdmY4Y1hq
            Mm1neVJ4bXYvQ05yc1hMWlZKWGVUd1kK7YTqAm325ehgHNHQ6ilJWDEPkIk+qgrv
            9tCELS7ECR8vZ9FfKyk6ztdQE9wYRpU8bZg+SYQLWyggDpxGbwaSKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T18:23:17Z"
    mac: ENC[AES256_GCM,data:emSmviAngitjKx5ftmbUnDv9kxGHGTjWXan5LwuNx2pI4PQDTw/VefJMHyzee5DLrSTPqRxBqQBiCVuqH5JYoS3uHW/WVZUfrwQtJPQcEBmY69Q7t92qSkyg5yJ2OgHTYlBXqYW7K6pFDYdrgFafJZYhFRn5URDLG159pYrPVJc=,iv:PaXqUlVulL5euyWeOtx6lg8E6OT2XZgAQe1RvntcwUc=,tag:ct254wruXPIOUsxi5JUoMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
