---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel-hub
  namespace: beszel
spec:
  strategy:
  type: RollingUpdate
  selector:
    matchLabels:
      app: beszel-hub
  template:
    metadata:
      labels:
        app: beszel-hub
    spec:
      containers:
        - name: beszel-hub
          image: ghcr.io/henrygd/beszel/beszel:0.16.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          envFrom:
            - secretRef:
                name: beszel-hub-secrets
            - configMapRef:
                name: beszel-hub-config
          volumeMounts:
            - name: beszel-hub-data
              mountPath: /beszel_data
      volumes:
        - name: beszel-hub-data
          persistentVolumeClaim:
            claimName: beszel-hub-data
