apiVersion: v1
kind: Secret
metadata:
    name: basic-auth
    namespace: grafana
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:DOrTyKiy85DgLIicsIybzoUK6cc5BjmYEg==,iv:WNyfqJjaEmMPwvrchLS0GEX4B3XUnBCY34VQFmyqfz0=,tag:ndO7I6tR4FWGbHOGnfNKMg==,type:str]
    password: ENC[AES256_GCM,data:wk7S9VD66zUhtO7ysOdsdxNu9sZe5eAJT0NmIiNV,iv:pRWhnhnJZVo6hmaxWSDOyN5H9oFypNpr++ZZNRExCYQ=,tag:6dTG75dioIK1BpWr1uIfUw==,type:str]
sops:
    age:
        - recipient: age1ys5az3gtql0nut2ldf88waz3jkmwzuvfl7gcrn9sja2luvnaud2s6u3834
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQkJxZkFaRHdDQ1YvRVlw
            NFFzeWhuazRXOThaS1MzN1ZnbnRrMjRudm1VClg1SnNWOWdxaGpjM3Zja0RLRDZP
            NGZ4QlVxVStid3B2RlFNVldIZ0x0ZjQKLS0tIHJhZkpCc0UxTzZ1bjlCdmY4Y1hq
            Mm1neVJ4bXYvQ05yc1hMWlZKWGVUd1kK7YTqAm325ehgHNHQ6ilJWDEPkIk+qgrv
            9tCELS7ECR8vZ9FfKyk6ztdQE9wYRpU8bZg+SYQLWyggDpxGbwaSKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-01T20:10:33Z"
    mac: ENC[AES256_GCM,data:5MW5CPbq5l3BB+nclACdfWOvwG1cmSzgBuyfvGGkwaCcgS+htQUQOCiuO3RoOFFoCwabxbHWvDc7g1K1Mwm2ttSbc8I6vXFoMMWr3222MPiIHmLY4fcUDubuExdJ7pzy5WUwqj5nhz+ErK7jrWv68yXtk3BJASRHZCWkF6NQNUk=,iv:n7RrE4WFvSVLLqwAg5gkkkgDWKVZCgkPjlyYHY9e248=,tag:NOoXE7BaBzLRIZCQZRpJ8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
