resources:
  - ./cert-manager
  - ./cloudnativepg
  - ./nfs-subdir-external-provisioner
  - ./redis
  - ./cloudflared
  - ./portainer
  - ./homarr
  - ./intel-device-plugin-operator
  - ./intel-gpu-device-plugin
  - ./node-feature-discovery
  - ./pgadmin
  - ./monitoring
  - ./grafana
