---
apiVersion: v1
kind: Service
metadata:
  namespace: it-tools
  name: it-tools
  labels:
    app: it-tools
spec:
  type: ClusterIP
  selector:
    app: it-tools
  ports:
    - port: 80
      name: http
