---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: zeus
  namespace: kube-system
spec:
  loadBalancer:
    serversTransport: insecure-transport
    servers:
      - url: "https://192.168.0.73:8006"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zeus
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`zeus.maurovi.ch`)
      middlewares:
        - name: gzip
      services:
        - name: zeus
          kind: TraefikService
  tls: {}
