---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox-insecure
  namespace: kube-system
spec:
  insecureSkipVerify: true
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-zeus-endpoint
  namespace: kube-system
  labels:
    kubernetes.io/service-name: external-zeus
addressType: IPv4
ports:
  - name: https
    protocol: TCP
    port: 8006
endpoints:
  - addresses:
      - "192.168.0.73"
---
apiVersion: v1
kind: Service
metadata:
  name: external-zeus
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: https
      port: 8006
      targetPort: 8006
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: external-zeus
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`zeus.maurovi.ch`)
      services:
        - name: external-zeus
          port: 8006
          scheme: https
