---
apiVersion: v1
kind: Service
metadata:
  name: lazylibrarian
  namespace: lazylibrarian
spec:
  type: ClusterIP
  selector:
    app: lazylibrarian
  ports:
    - port: 80
      targetPort: 5299
      name: http
