resources:
  - ../base
  - ./miniflux
  - ./paperless-ngx
  - ./recipes
  - ./vaultwarden
  - ./jellyfin
  - ./jellyseerr
  - ./radarr
  - ./sonarr
  - ./prowlarr
  - ./sabnzbd
  - ./gotify
  - ./apprise
  - ./beszel
  - ./gatus
  - ./audiobookshelf
