---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: recipes
spec:
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      containers:
        - name: recipes
          image: ghcr.io/tandoorrecipes/recipes:2.3.3
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: recipes-secrets
          volumeMounts:
            - mountPath: /opt/recipes/staticfiles
              name: recipes-staticfiles
            - mountPath: /opt/recipes/mediafiles
              name: recipes-mediafiles
      volumes:
        - name: recipes-staticfiles
          persistentVolumeClaim:
            claimName: recipes-staticfiles
        - name: recipes-mediafiles
          persistentVolumeClaim:
            claimName: recipes-mediafiles
