---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprise
  namespace: apprise
spec:
  selector:
    matchLabels:
      app: apprise
  template:
    metadata:
      labels:
        app: apprise
    spec:
      containers:
        - name: apprise
          image: caronc/apprise:1.3
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "200Mi"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: apprise-config
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: apprise-data
              mountPath: /config
      volumes:
        - name: apprise-data
          persistentVolumeClaim:
            claimName: apprise-data
