---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cn-postgresql-cluster
  namespace: cnpg-system
spec:
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    # Relying on PostgreSQL's native replication mechanism across instances
    # and scheduled backups to external S3 bucket.
    # If a major fail occurs, the db can be initialized from the backup.
    # Therefore, 'local-path' and not e.g. nfs with replicated RAID drives
    # and because of speed and less overhead.
    # Following cnpg best practice.
    storageClass: local-path
    size: 10Gi
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  enableSuperuserAccess: true
  primaryUpdateStrategy: unsupervised
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        operator: Exists
        effect: NoSchedule
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cn-barman-cloud-cloudflare-object-store
  managed:
    roles:
      - name: app
        createdb: true
        login: true
      - name: miniflux
        createdb: true
        login: true
        superuser: true
        passwordSecret:
          name: miniflux-db-auth
      - name: paperlessngx
        createdb: true
        login: true
        passwordSecret:
          name: paperless-ngx-db-auth
      - name: recipes
        createdb: true
        login: true
        passwordSecret:
          name: recipes-db-auth
      - name: vaultwarden
        createdb: true
        login: true
        passwordSecret:
          name: vaultwarden-db-auth
      - name: jellyseerr
        createdb: true
        login: true
        passwordSecret:
          name: jellyseerr-db-auth
      - name: radarr
        createdb: true
        login: true
        passwordSecret:
          name: radarr-db-auth
      - name: sonarr
        createdb: true
        login: true
        passwordSecret:
          name: sonarr-db-auth
      - name: prowlarr
        createdb: true
        login: true
        passwordSecret:
          name: prowlarr-db-auth
      - name: gotify
        createdb: true
        login: true
        passwordSecret:
          name: gotify-db-auth
      - name: gatus
        createdb: true
        login: true
        passwordSecret:
          name: gatus-db-auth
