---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-route
  namespace: external-routes
spec:
  ports:
    - port: 443
      targetPort: 8006
      name: https
  type: ExternalName
  externalName: 192.168.0.73
